# Lesson 2: Nature of Data

## 5. Encoding using sklearn

In [1]:
from sklearn import preprocessing
import pandas


# creating sample data
sample_data = {'name': ['Ray', 'Adam', 'Jason', 'Varun', 'Xiao'],
'health':['fit', 'slim', 'obese', 'fit', 'slim']}
# storing sample data in the form of a dataframe
data = pandas.DataFrame(sample_data, columns = ['name', 'health'])
print data
print

'''
# Mapping Relations
fit : 0
obese: 1
slim: 2
'''
'''
# 1. Label Encoder
'''
label_encoder = preprocessing.LabelEncoder()
label_encoder.fit(data['health'])

print 'Label Encoder:'
print label_encoder.transform(data['health'])
print label_encoder.fit_transform(data['health'])
print

'''
# 2. One-hot Encoder
'''
print 'get_dummies:'
print pandas.get_dummies(data['health'])
print

ohe = preprocessing.OneHotEncoder() # creating OneHotEncoder object
label_encoded_data = label_encoder.fit_transform(data['health'])
print 'One-hot Encoder:'
print ohe.fit_transform(label_encoded_data.reshape(-1,1)).toarray()


    name health
0    Ray    fit
1   Adam   slim
2  Jason  obese
3  Varun    fit
4   Xiao   slim

Label Encoder:
[0 2 1 0 2]
[0 2 1 0 2]

get_dummies:
   fit  obese  slim
0    1      0     0
1    0      0     1
2    0      1     0
3    1      0     0
4    0      0     1

One-hot Encoder:
[[ 1.  0.  0.]
 [ 0.  0.  1.]
 [ 0.  1.  0.]
 [ 1.  0.  0.]
 [ 0.  0.  1.]]


## 6. Quiz: One-Hot Encoding

[The comparison between LabelEncoder and OneHotEncoder](https://blog.csdn.net/u012560212/article/details/53405338)

In [50]:
# In this exercise we'll load the titanic data (from Project 0)
# And then perform one-hot encoding on the feature names

import numpy as np
import pandas as pd

# Load the dataset
X = pd.read_csv('titanic-data.csv')
# Limit to categorical data
X = X.select_dtypes(include=[object])
print X.head()

                                                Name     Sex  \
0                            Braund, Mr. Owen Harris    male   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female   
2                             Heikkinen, Miss. Laina  female   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female   
4                           Allen, Mr. William Henry    male   

             Ticket Cabin Embarked  
0         A/5 21171   NaN        S  
1          PC 17599   C85        C  
2  STON/O2. 3101282   NaN        S  
3            113803  C123        S  
4            373450   NaN        S  


In [57]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

# TODO: create a LabelEncoder object and fit it to each feature in X.
# The label encoder only takes a single feature at a time!
# for feature in X:
#     X[feature] = le.fit_transform(X[feature])

X = X.apply(LabelEncoder().fit_transform)
print "After Labels Encoded:"
print X.head()


After Labels Encoded:
   Name  Sex  Ticket  Cabin  Embarked
0   108    1     523      0         4
1   190    0     596    768         2
2   353    0     669    509         4
3   272    0      49    742         4
4    15    1     472    510         4


In [58]:
# TODO: create a OneHotEncoder object, and fit it to all of X.
enc = OneHotEncoder() #no fitting here, happens during the transfomartion

#TODO: transform the categorical titanic data, and store the transformed labels in the variable `onehotlabels`
onehotlabels = enc.fit_transform(X) #fit and transform in one step
print onehotlabels.toarray()

[[ 0.  0.  0. ...,  0.  0.  1.]
 [ 0.  0.  0. ...,  1.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  1.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  1.]
 [ 0.  0.  0. ...,  1.  0.  0.]
 [ 0.  0.  0. ...,  0.  1.  0.]]
